name: Deploy Website

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-2022
    permissions:
      contents: write
    
    steps:
      - name: Checkout Pt-Framework
        uses: actions/checkout@v4

      - name: Checkout Pt
        uses: actions/checkout@v4
        with:
          repository: Pt-Framework/Pt
          path: pt-source

      - name: Install Doxygen 1.8.6 (Windows)
        shell: pwsh
        run: |
          $url = "https://sourceforge.net/projects/doxygen/files/rel-1.8.6/doxygen-1.8.6.windows.x64.bin.zip/download"
          Invoke-WebRequest -Uri $url -OutFile "doxygen.zip" -UserAgent "NativeHost"
          Expand-Archive -Path "doxygen.zip" -DestinationPath "doxygen-bin"

          echo "$pwd\doxygen-bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build Website
        shell: pwsh
        run: |
          cd pt-source/doc
          doxygen Doxyfile

          New-Item -Path ".nojekyll" -ItemType File -Force

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pt-source/doc
          branch: main
          clean: true
